# Generated by Django 3.2.20 on 2023-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragraph', '0002_auto_20230716_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphmodel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='段落標題'),
        ),
    ]
