# Generated by Django 3.2.20 on 2023-07-15 13:36

import base_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='資料創建時間')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='資料最後更新時間')),
                ('title', models.CharField(max_length=50, verbose_name='標題')),
                ('introduction', models.TextField(max_length=500, verbose_name='簡介')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否發佈')),
                ('timestamp', models.DateTimeField(verbose_name='時間戳記(要顯示的日期時間)')),
                ('create_user', models.OneToOneField(on_delete=models.SET(base_app.models.get_anonymous_user), related_name='articlemodel_create_user', to=settings.AUTH_USER_MODEL, verbose_name='資料創建者')),
                ('updated_user', models.OneToOneField(on_delete=models.SET(base_app.models.get_anonymous_user), related_name='articlemodel_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='資料最後更新者')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
