# Generated by Django 3.2.20 on 2023-07-16 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20230715_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlehavemediamodel',
            name='report_url',
            field=models.URLField(default='', max_length=150, verbose_name='媒體引用連結'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 10, 41, 3, 118765), verbose_name='時間戳記(要顯示的日期時間)'),
        ),
        migrations.AlterModelTable(
            name='articlehaveimagemodel',
            table='article_have_image',
        ),
    ]
