# Generated by Django 3.2.20 on 2023-07-16 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20230716_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間戳記(要顯示的日期時間)'),
        ),
    ]
