# Generated by Django 3.2.20 on 2023-07-17 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20230716_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='publish_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='發佈日期'),
        ),
    ]
