# Generated by Django 3.2.20 on 2023-07-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_articlemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehaveimagemodel',
            name='source',
            field=models.TextField(default='', verbose_name='圖片來源(檔案來源)'),
        ),
        migrations.AlterField(
            model_name='articlehavemediamodel',
            name='report_url',
            field=models.TextField(default='', verbose_name='媒體引用連結'),
        ),
    ]
