# Generated by Django 3.2.20 on 2023-07-15 15:19

import base_app.models
from django.conf import settings
from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='資料創建時間')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='資料最後更新時間')),
                ('code', models.CharField(default='', max_length=50, verbose_name='媒體代號')),
                ('name', models.CharField(default='', max_length=50, verbose_name='媒體名稱')),
                ('image', models.ImageField(upload_to=media.models.media_image_path, verbose_name='媒體圖片')),
                ('create_user', models.OneToOneField(on_delete=models.SET(base_app.models.get_anonymous_user), related_name='mediamodel_create_user', to=settings.AUTH_USER_MODEL, verbose_name='資料創建者')),
                ('updated_user', models.OneToOneField(on_delete=models.SET(base_app.models.get_anonymous_user), related_name='mediamodel_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='資料最後更新者')),
            ],
            options={
                'db_table': 'media',
            },
        ),
    ]
