# Generated by Django 3.2.20 on 2023-07-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20230719_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='image_source',
            field=models.TextField(default='', verbose_name='媒體圖片來源(檔案來源)'),
        ),
    ]
